name: Metrics
on:
  # Schedule daily updates.
  schedule: [{ cron: "0 0 * * *" }]
  # Run workflow manually.
  workflow_dispatch:
  # Run workflow when pushing on main.
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Base content.
          base: metadata, repositories
          # commits_authoring: Arvin·趙, ArvinZJC, tomzjc@qq.com, zjcarvin@outlook.com, SteveJobz@isarvin.com
          repositories_affiliations: ""

          # Core.
          committer_message: "chore: update metrics"
          # config_order: languages, stargazers
          config_output: svg
          config_timezone: Asia/Shanghai
          filename: my_metrics.*
          output_condition: data-changed
          token: ${{ github.token }}

          # Languages activity.
          plugin_languages: yes
          plugin_languages_limit: 0

          # Lines of code changed.
          plugin_lines: yes
          plugin_lines_sections: base

          # Repositories traffic.
          plugin_traffic: yes

          # Stargazers.
          # plugin_stargazers: yes
          # plugin_stargazers_charts: no
          # plugin_stargazers_worldmap: yes
          # plugin_stargazers_worldmap_sample: 200
          # plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
