# Refer to: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Metrics
on:
  # Schedule daily updates.
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit.
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}

          # Base content.
          base: metadata
          commits_authoring: Arvin·趙, ArvinZJC, tomzjc@qq.com, zjcarvin@outlook.com

          # Core.
          committer_message: "chore: update metrics"
          config_order: isocalendar, languages, activity
          config_timezone: Asia/Shanghai
          filename: my_metrics.*
          user: ArvinZJC

          # Isometric commit calendar.
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Recent activity.
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_load: 100
