# Refer to: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Metrics
on:
  # Schedule daily updates.
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit.
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Base content.
          base: metadata
          commits_authoring: Arvin·趙, ArvinZJC, tomzjc@qq.com, zjcarvin@outlook.com
          repositories_affiliations: ""

          # Core.
          committer_message: "chore: update metrics"
          config_order: isocalendar, languages, activity
          config_timezone: Asia/Shanghai
          filename: my_metrics.*
          token: ${{ github.token }}
          user: ArvinZJC

          # Isometric commit calendar.
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Most used languages.
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Recent activity.
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 100
          plugin_activity_visibility: all
